openapi: 3.0.2
info:
  title: UADS Backend
  version: 1.0.0
  description: API's used for UADS Backend
  contact:
    name: Web Development and Consulting Club
    url: https://wdcc.co.nz
    email: wdcc.uoa@gmail.com
paths:
  /event:
    summary: End point to do with events
    get:
      tags:
        - Event
      parameters:
        - name: filter
          description: Sort by filter
          schema:
            type: string
          in: query
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
          description: Valid request
      operationId: GET_EVENT
      summary: Get all events
      description: Get all events, and filtered.
    put:
      tags:
        - Event
      responses:
        '200':
          description: Successfully modify the events.
        '404':
          description: |
            An error has occurred.
      operationId: PUT_EVENT
      summary: Update the events
      description: |
        Allows for the update of events.
    post:
      tags:
        - Event
      responses:
        '200':
          description: Successfully posted events
        '404':
          description: Error has occurred
      operationId: POST_EVENTS
      summary: Post events
      description: |
        Allows the posting of events
    delete:
      tags:
        - Event
      responses:
        '200':
          description: Event successfully deleted
        '404':
          description: An error has occurred.
      operationId: DELETE_EVENT
      summary: Deleting an event
      description: |
        Deleting a specific event type
  /user:
    summary: End point to do with users
    get:
      tags:
        - User
      parameters:
        - name: club
          description: the members of a given club
          schema:
            type: string
          in: query
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: success
      operationId: GET_USER
      summary: Getting User
      description: Get all users / get all users in a particular club
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      tags:
        - User
      responses:
        '200':
          description: Successful change in the user management.
        '404':
          description: An error has occurred.
      operationId: PUT_USER
      summary: Modify the user
      description: User management for the admins.
    post:
      requestBody:
        description: User to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      tags:
        - User
      responses:
        '200':
          description: success
        '404':
          description: fails
      operationId: POST_USER
      summary: Add user
      description: Create user upon registration
    delete:
      tags:
        - User
      responses:
        '200':
          description: Successfully deleted user
        '404':
          description: An error has occurred.
      operationId: DELETE_USER
      summary: Delete user
      description: Allows to delete user from UADS.
  /club:
    summary: End point to do with club
    get:
      tags:
        - Club
      parameters:
        - name: name
          description: ''
          schema:
            type: string
          in: query
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Club'
          description: Success
      operationId: GET_CLUB
      summary: Get clubs
      description: Get all clubs, and club by name.
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Club'
        required: true
      tags:
        - Club
      responses:
        '200':
          description: Successfully modified club
        '404':
          description: An error has occurred.
      operationId: PUT_CLUB
      summary: Modify the club
      description: Modify the club things i.e. club name.
    post:
      tags:
        - Club
      responses:
        '200':
          description: Successful post
      operationId: POST_CLUB
      summary: Create club
    delete:
      tags:
        - Club
      responses:
        '200':
          description: Successfully deleted information.
        '404':
          description: An error occurred.
      operationId: DELETE_CLUB
      summary: Delete things from club
      description: Allows for the deletion of information the club path.
  /sponsor:
    summary: End point to do with sponsors
    get:
      tags:
        - Sponsor
      parameters:
        - name: filter
          description: name filter/search?
          schema:
            type: string
          in: query
        - name: discount
          description: Get by discount
          schema:
            type: string
          in: query
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sponsor'
          description: Success
      operationId: GET_SPONSOR
      summary: Get sponsors
      description: Get all sponsors, sponsor of a discount, and filtered.
    put:
      tags:
        - Sponsor
      responses:
        '200':
          description: Successfully modify the sponsors.
        '404':
          description: An error has occurred.
      operationId: PUT_SPONSOR
      summary: Modify the sponsor details
      description: Allows the modification of the sponsors.
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sponsor'
        required: true
      tags:
        - Sponsor
      responses:
        '200':
          description: Successfully posts sponsor
        '404':
          description: Error has occurred
      operationId: POST_SPONSOR
      summary: Post sponsors
      description: Allows the posting of sponsors
    delete:
      tags:
        - Sponsor
      responses:
        '200':
          description: |
            Successfully deleted sponsor
        '404':
          description: An error has occurred.
      operationId: DELETE_SPONSOR
      summary: Delete sponsor
      description: |
        Deleting a sponsor from UADS.
  /discount:
    summary: End point to do with discount
    get:
      tags:
        - Discount
      parameters:
        - name: filter
          description: Sort by filter
          schema:
            type: string
          in: query
        - name: sponsor
          description: Get discounts from a particular sponsor
          schema:
            type: string
          in: query
          required: false
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Discount'
          description: Offers successfully received
      operationId: GET_DISCOUNT
      summary: Get Discounts
      description: Get all discounts, discounts of a sponsor, and filtered.
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Discount'
        required: true
      tags:
        - Discount
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Discount'
          description: Discount successfully put.
      operationId: PUT_DISCOUNT
      summary: Modify discounts
      description: Allows admins to modify discounts
    post:
      tags:
        - Discount
      responses:
        '200':
          description: |
            Successfully posted discount
        '404':
          description: Error has occurred
      summary: Post discount
      description: Allows the posting of discounts.
    delete:
      tags:
        - Discount
      responses:
        '200':
          description: Successfully deleted offer
      operationId: DELETE_DISCOUNT
      summary: Deleting the offers
      description: Deleting offers in UADS.
  /user/{id}:
    summary: Route for Users By ID
    get:
      tags:
        - User
      parameters:
        - name: id
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          description: Success
      operationId: GET_USER_ID
      summary: Getting users by ID
    parameters:
      - name: id
        schema:
          type: integer
        in: path
        required: true
  /club/{id}:
    put:
      tags:
        - Club
      parameters:
        - name: id
          schema:
            type: string
          in: path
          required: true
      responses:
        '200':
          description: Good
      operationId: GET_CLUB_ID
      summary: Getting clubs by ID
    parameters:
      - name: id
        schema:
          type: integer
        in: path
        required: true
components:
  schemas:
    Sponsor:
      description: Data type to store sponsors using the UADS App
      required:
        - uuid
        - name
        - desc
      type: object
      properties:
        uuid:
          description: The UUID of the sponsor
          type: string
        name:
          description: The name of the sponsor
          type: string
        desc:
          description: The description of the sponsor
          type: string
    Club:
      description: Data type to store clubs using the UADS App
      required:
        - uuid
        - name
      type: object
      properties:
        uuid:
          description: The UUID of the Club
          type: string
        name:
          description: The name of the club
          type: string
        desc:
          description: A club description
          type: string
        imagePath:
          description: A image of the club
          type: string
        admins:
          description: The admin(s) of the club
          type: array
          items:
            type: string
        sponsors:
          description: The UUID of the sponsor(s) of the club
          type: array
          items:
            type: string
        events:
          description: The events hosted by the club
          type: array
          items:
            type: string
    Event:
      description: Data type to store events using the UADS App
      required:
        - uuid
        - name
        - date
        - attendanceCap
        - club
      type: object
      properties:
        uuid:
          format: uuid
          description: The UUID of the event
          pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
          type: string
        name:
          description: The name of the event
          type: string
        date:
          format: date
          description: The starting Date of the event
          type: string
        imagePath:
          description: The path/url to an event image
          type: string
        attendanceCap:
          description: The maximum number of attendees, (-1 for no cap)
          minimum: -1
          type: integer
        sponsors:
          description: The sponsor(s) of the event
          type: array
          items:
            type: string
        url:
          description: An external url for the event
          type: string
        club:
          description: The UUID of club(s) hosting the event
          type: array
          items:
            type: string
    User:
      description: A user of the app
      required:
        - uuid
      type: object
      properties:
        uuid:
          description: '> uuid of the users'
          type: string
    Discount:
      description: Discounts
      required:
        - sponsor
        - value
        - desc
        - uuid
      type: object
      properties:
        desc:
          description: The description of the discount
          type: string
        uuid:
          description: |
            The id of the discount
          type: integer
        sponsor:
          description: The sponsor of the discount
          type: string
        value:
          description: The value of the discount
          type: integer
